services:
  tubearchivist:
    container_name: "tubearchivist"
    restart: "unless-stopped"
    image: "bbilly1/tubearchivist"
    ports:
      - "8000:8000"
    volumes:
      - "media:/youtube"
      - "cache:/cache"
    environment:
      ES_URL: "http://archivist-es:9200"
      REDIS_CON: "redis://archivist-redis:6379"
      HOST_UID: "1000"
      HOST_GID: "1000"
      # Set your host name with protocol and port:
      TA_HOST: "http://tubearchivist.local:8000"
      # Your initial TA credentials:
      TA_USERNAME: "tubearchivist"
      # Your initial TA credentials:
      TA_PASSWORD: "verysecret"
      # Set password for Elasticsearch:
      ELASTIC_PASSWORD: "verysecret"
      # Set your time zone:
      TZ: "America/New_York"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: "2m"
      timeout: "10s"
      retries: "3"
      start_period: "30s"
    depends_on:
      - "archivist-es"
      - "archivist-redis"
  archivist-redis:
    image: "redis"
    container_name: "archivist-redis"
    restart: "unless-stopped"
    expose:
      - "6379"
    volumes:
      - "redis:/data"
    depends_on:
      - "archivist-es"
  archivist-es:
    # Only for amd64, or use official es 8.18.2:
    image: "bbilly1/tubearchivist-es"
    container_name: "archivist-es"
    restart: "unless-stopped"
    environment:
      # Matching Elasticsearch password:
      ELASTIC_PASSWORD: "verysecret"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: "true"
      discovery.type: "single-node"
      path.repo: "/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # Check for permission error when using bind mount, see readme:
      - "es:/usr/share/elasticsearch/data"
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es:
